### PR TITLE
Allow to build the keepalive module without building the android specific parts

### PR DESCRIPTION
**Pull request by piggz**

### CODE REVIEW

**Comment by jusa** [comment]
As the keepalive module doesn't really have anything specific to do with droid modules (other than needed on droid adaptations) I'd rather just split the whole module to its own repository.

**Comment by piggz** [comment]
thats fine , can i leave that with you then?

**Comment by jusa** [comment]
Yep, already pushed split code to https://git.sailfishos.org/jusa/pulseaudio-module-keepalive - soon in mer-core etc. I'll also make transitional change to droid-configs-device and drop the code from this package soon.

**Comment by jusa** [comment]
Now in mer-core.

**Pull request closed without merging**
