### PR TITLE
Update to PulseAudio 6.0

### PR DESCRIPTION
**Pull request by jusa**

### CODE REVIEW

**Comment by saukko** [comment]
We should fix the first line from .spec to do automatic pulseaudio version detection.

%define pulseaudio-version %{expand:%(rpm -q --qf '[%%{version}]' pulseaudio)}

after that lgtm.

**Comment by sledges** [comment]
Will this break compatibility on pa5 (SFE porters devices)?

**Comment by jusa** [comment]
@sledges Yes and no. Yes, as in out-of-tree modules built against 5.0 work only with 5.0, etc. No, as long as all out-of-tree PulseAudio modules are updated to build against 6.0 when PulseAudio is updated to 6.0 (which is exactly what is happening here). As I understand SFE devices get PulseAudio 6.0 normally as well so everything should work fine.

**Comment by jusa** [comment]
Updated packaging will dynamically check underlying PulseAudio version, and will build and package according to the found version.
So lets say from tag "6.0.35" depending on PulseAudio version either VERSION 5.0.35 or 6.0.35 is built.
This also highlights the fact that the major.minor version denotes supported PulseAudio version, micro denotes the actual module version.
Only drawback is that if tag 6.0.35 is built against PulseAudio 5.0, resulting package naturally has version 6.0.35, which goes against the "major.minor should match PulseAudio version" thinking. But this should be only transitional hiccup, and the module versioning still shows 5.0.35.

**Comment by saukko** [comment]
LGTM

**Pull request merged**
