### PR TITLE
Fix voicecall record with certain devices.

### LINKED ISSUE #67: Voicecall recording issues
Hi @jusa 
I'm experiencing issues while recording calls natively in my Xperia X with SailFish X.
The problem is that the audio from the voice calls is not recorded properly, while the audio recorded while I speak to the mic (without call established) is recorded fine.
I've been tracing with pulseaudio and seems to me that there could be a problem with <module-droid-card.c>, the driver for <source.primary> in my device configuration.

Here's how I tested:
```

[nemo@Sailfish CallRecordings]$ pactl set-card-profile 0 voicecall-record
[nemo@Sailfish CallRecordings]$ parec --record --device=sink.primary.monitor --file-format=wav --verbose output.wav
Opening a recording stream with sample specification 's16le 2ch 44100Hz' and channel map 'front-left,front-right'.
Connection established.
Stream successfully created.
Buffer metrics: maxlength=4194304, fragsize=352800
Using sample spec 's16le 2ch 44100Hz', channel map 'front-left,front-right'.
Connected to device source.primary (index: 2, suspended: no).
Stream moved to device source.primary (2, not suspended).
Got signal, exiting.ncy: 18843 usec.
```

My test consists in recording, first a voicecall, then hangup the call and speak directly to the microphone (this is reflected by the "Stream moved to device..." message in the log I attached).
When I listen to the recorded file the part corresponding to the voicecall is wrong and the part where I speak to the microphone is OK.
I can provide a sample if you think it would be useful.
Also, there's a question opened in TJC and this may be a redundant request... let me know :-D
https://together.jolla.com/question/170695/call-recording-broken-audio/
Regards.

### PR DESCRIPTION
**Pull request by jusa**
Fixes #67

### CODE REVIEW

**Comment by PaskoMoto** [comment]
Hi, @jusa 

Thank you for your quick answer. :-)
I was wondering: Coult it be possible to 'temporarily' solve the problem by editing the pulseaudio config files?

Regards.

**Comment by jusa** [comment]
@PaskoMoto unfortunately not, as the setting is defined during build time. If you want I can provide you with updated rpms to test.

**Comment by PaskoMoto** [comment]
Hi @jusa 

OK. That would be great. 

I use voice call recording very often and will be able to test it throughouly.

Best regards.

**Comment by spiiroin** [comment]
:+1:

**Pull request merged**
